### ISSUE TITLE
"Launch External Terminal" not working

### ISSUE THREAD

**Issue by arifcelik56** [microsoft/vscode-java-debug#1074]
[provide a description of the issue]

in vscode a blank terminal screen opens and the error in the picture comes.

##### Environment
- Operating System: Pop!_OS 21.04
- JDK version: 17.0.1+12
- Visual Studio Code version: 1.62.2
- Java extension version: v0.18.6
- Java Debugger extension version: v0.36.0

!ENTRY java-debug 4 0 2021-11-14 23:02:30.289
!MESSAGE [error response][launch]: Failed to launch debuggee in terminal. Reason: Failed to launch debuggee in terminal. Reason: java.util.concurrent.TimeoutException: timeout
!STACK 0
com.microsoft.java.debug.core.DebugException: Failed to launch debuggee in terminal. Reason: Failed to launch debuggee in terminal. Reason: java.util.concurrent.TimeoutException: timeout
	at com.microsoft.java.debug.core.adapter.handler.LaunchWithDebuggingDelegate.lambda$launchInTerminal$0(LaunchWithDebuggingDelegate.java:157)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer$1.run(AbstractProtocolServer.java:192)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)

##### Current Result
![resim](https://user-images.githubusercontent.com/46600975/141697214-0492cc37-536f-4394-a6eb-8facd4eaad6a.png)

**Comment by testforstephen** [comment]
could you try integrated terminal to see if it works?

**Comment by arifcelik56** [comment]
> could you try integrated terminal to see if it works?

integrated terminal it works but i wanna launch program in external (gnome) terminal for some tests. is there a way I can run ?

**Comment by testforstephen** [comment]
No clue what's wrong in your system. I tried macOS, windows, ubuntu, the external terminal all works.

**Comment by arifcelik56** [comment]
> No clue what's wrong in your system. I tried macOS, windows, ubuntu, the external terminal all works.

Is there a log file or something similar that I can upload to provide information?

**Comment by pierre-cm** [comment]
In my case, modifying the default value of `terminal.external.linuxExec` user setting from `x-terminal-emulator` to `gnome-terminal` solved the issue.
