### ISSUE TITLE
TestNG tests stuck at Resolving launch configuration

### ISSUE THREAD

**Issue by realqpat** [microsoft/vscode-java-debug#1221]
Can no longer run TestNG tests

##### Environment
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.10.136-1-MANJARO
Sandboxed: No

Everything used to work fine for well over a year..All of sudden I can no longer run any TestNG tests
I can't get past  Resolving launch configuration 

Tried everything I could think of. What do you guys need in terms of logs to help with this ?

**Comment by realqpat** [comment]
Is the following related ?? it is appearing in my Output console
```
[Error - 6:02:02 PM] Sep 16, 2022, 6:02:02 PM Error in calling delegate command handler
Given URI does not belong to an existing Java source file.
org.eclipse.core.runtime.CoreException: Given URI does not belong to an existing Java source file.
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.isTestFile(ProjectCommand.java:197)
	at org.eclipse.jdt.ls.core.internal.JDTDelegateCommandHandler.executeCommand(JDTDelegateCommandHandler.java:84)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:529)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by testforstephen** [comment]
@jdneo Could you please take a look at this issue?

**Comment by jdneo** [comment]
How do you open your project? Is that a symlink folder? Or do you launch it via `Remote`?

A minimal sample project to reproduce this issue could be helpful as well.

**Comment by Maa-ddy** [comment]
I had the same issue. I fixed it by re-installing the whole java extension pack

**Comment by realqpat** [comment]
Thanks @Maa-ddy  ..Following your suggestion, instead of re-installing I went with disabling the extension, re-enabled it and restart vs code
It's working now !!

**Comment by realqpat** [comment]
After much troubleshooting, isolated the issue to Spring (since re-enabling those extensions brings the issue back)
See here https://github.com/spring-projects/sts4/issues/847
So removing (or leaving them disabled) all Spring extensions (Spring Initializ, Spring Boot Tools and Spring Boot Dashboard) fixed it
Waiting for this bug to be fixed before reenabling them

**Comment by BoykoAlex** [comment]
Do you mind uninstalling java related extensions and then installing them. Someone mentioned that after re-installing java extensions the issue cannot be reproduced

**Comment by realqpat** [comment]
I did uninstall all Spring extensions and reinstalled but was still faced with the same issue.
What worked for me is to either have them disabled or uninstalled

**Comment by BoykoAlex** [comment]
@realqpat One thing to try would be to find Boot-java › Live-information › Automatic-connection under Spring Boot Tools -> Features settings and turn it off. Any difference?

**Comment by realqpat** [comment]
@BoykoAlex That does not make any difference. Still can't lunch tests. I turned it off and confirmed it's indeed off
```"boot-java.live-information.automatic-connection.on": false```

**Comment by realqpat** [comment]
Oh...I see that it was just fixed :) 
https://github.com/spring-projects/sts4/issues/847#issuecomment-1271822585
