### ISSUE TITLE
Cannot be installed either manually or from install button in vscode

### ISSUE THREAD

**Issue by levihuayuzhang** [microsoft/vscode-java-debug#1229]
[provide a description of the issue]

##### Environment
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-48-generic Ubuntu 22.04
Sandboxed: No

## Shows following log:

[2022-10-01 12:09:59.959] [renderer1] [error] ["Invalid: Corrupt ZIP: end of central directory record signature not found","    at G.downloadExtension (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:170668)","    at async G.doRun (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:169610)"]
[2022-10-01 12:09:59.982] [renderer1] [error] Corrupt ZIP: end of central directory record signature not found: Invalid: Corrupt ZIP: end of central directory record signature not found
    at G.downloadExtension (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:170668)
    at async G.doRun (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:83:169610)

**Comment by testforstephen** [comment]
Is it only for Java debugger? do you see errors for other extensions?

**Comment by levihuayuzhang** [comment]
> Is it only for Java debugger? do you see errors for other extensions?

I think it's only happened for java debugger. Other extensions (even other extension include in java extensions pack)works fine. 

Besides I think it's a linux specific or Ubuntu 2204 specific problem. Because it works fine on my Mac.

BTW, The Code was installed from official web site through deb.

**Comment by levihuayuzhang** [comment]
> The artifact file of Java Debugger are shared by all platforms, looks like some network issue on your Linux. And I also tried it on Ubuntu, no problems on my side.
> 
> 
> 
> Java Debugger just released a new version 0.45.0 today, could you try again with the new version?

Sorry I already move my working platform to my Mac. ButI can confirm Mac works fine.
