### ISSUE TITLE
Conditional Breakpoint got error code in reply:504

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-debug#1250]
```
!MESSAGE [ConditionalBreakpoint]: Got error code in reply:504
!STACK 1
org.eclipse.debug.core.DebugException: Got error code in reply:504
	at org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine$EvalRunnable.run(ASTEvaluationEngine.java:920)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread$ThreadJob.run(JDIThread.java:3481)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.sun.jdi.InternalException: Got error code in reply:504
	at org.eclipse.jdi.internal.MirrorImpl.defaultReplyErrorHandler(MirrorImpl.java:302)
	at org.eclipse.jdi.internal.ThreadReferenceImpl.frames(ThreadReferenceImpl.java:286)
	at com.microsoft.java.debug.core.adapter.StackFrameManager.lambda$reloadStackFrames$0(StackFrameManager.java:40)
	at java.base/java.util.HashMap.compute(HashMap.java:1316)
	at com.microsoft.java.debug.core.adapter.StackFrameManager.reloadStackFrames(StackFrameManager.java:35)
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider$1.invokeComplete(JdtEvaluationProvider.java:320)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.invokeMethod(JDIThread.java:1018)
	at org.eclipse.jdt.internal.debug.core.model.JDIObjectValue.sendMessage(JDIObjectValue.java:162)
	at org.eclipse.jdt.internal.debug.eval.ast.instructions.SendMessage.execute(SendMessage.java:60)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.Interpreter.execute(Interpreter.java:69)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine$EvalRunnable$1EvaluationRunnable.run(ASTEvaluationEngine.java:842)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.runEvaluation(JDIThread.java:821)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine$EvalRunnable.run(ASTEvaluationEngine.java:895)
	... 2 more
!SUBENTRY 1 org.eclipse.jdt.debug 4 0 2022-10-31 11:09:23.701
!MESSAGE Got error code in reply:504
!STACK 0
com.sun.jdi.InternalException: Got error code in reply:504
	at org.eclipse.jdi.internal.MirrorImpl.defaultReplyErrorHandler(MirrorImpl.java:302)
	at org.eclipse.jdi.internal.ThreadReferenceImpl.frames(ThreadReferenceImpl.java:286)
	at com.microsoft.java.debug.core.adapter.StackFrameManager.lambda$reloadStackFrames$0(StackFrameManager.java:40)
	at java.base/java.util.HashMap.compute(HashMap.java:1316)
	at com.microsoft.java.debug.core.adapter.StackFrameManager.reloadStackFrames(StackFrameManager.java:35)
	at com.microsoft.java.debug.plugin.internal.eval.JdtEvaluationProvider$1.invokeComplete(JdtEvaluationProvider.java:320)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.invokeMethod(JDIThread.java:1018)
	at org.eclipse.jdt.internal.debug.core.model.JDIObjectValue.sendMessage(JDIObjectValue.java:162)
	at org.eclipse.jdt.internal.debug.eval.ast.instructions.SendMessage.execute(SendMessage.java:60)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.Interpreter.execute(Interpreter.java:69)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine$EvalRunnable$1EvaluationRunnable.run(ASTEvaluationEngine.java:842)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread.runEvaluation(JDIThread.java:821)
	at org.eclipse.jdt.internal.debug.eval.ast.engine.ASTEvaluationEngine$EvalRunnable.run(ASTEvaluationEngine.java:895)
	at org.eclipse.jdt.internal.debug.core.model.JDIThread$ThreadJob.run(JDIThread.java:3481)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by testforstephen** [comment]
Reproduce steps:

```java
public class Demo {
    public static String getName(String value) {
        return value; // Add a conditional breakpoint with the expression value.equals("m2")
    }

    public static void main(String[] args) {
        call("me");
        System.out.println(getName("m2"));
    }

    public static void call(String value) {
        System.out.println(getName(value));
    }
}
```

Debug this program, it will get an error as follows.
![image](https://user-images.githubusercontent.com/14052197/198931708-8ef4d063-2269-4699-9087-6e3338d951f2.png)

**Comment by exetroncorp** [comment]
Hello i have got the same error with vscode debuger on local variable panel Failed to get variables. Reason: com.sun.jdi.InternalException: Got error code in reply:35.

Any idea ? using java 17.0.6 and latest vscode and extension , simple hello world spring boot.

![image](https://user-images.githubusercontent.com/117201867/222169526-50b82562-0c8e-4cf8-b737-33c3cf55adaf.png)

**Comment by christianapopoola** [comment]
I'm also having this issue, with the error. Any ideas on how to fix?
