### ISSUE TITLE
No delegateCommandHandler for vscode.java.resolveMainMethod

### ISSUE THREAD

**Issue by HackerJem** [microsoft/vscode-java-debug#1449]
![Screenshot (284)](https://github.com/microsoft/vscode-java-debug/assets/161212847/aab64207-5d40-4c98-99aa-011d70bd1664)
[provide a description of the issue]

##### Environment
- Operating System:
- JDK version:
- Visual Studio Code version:
- Java extension version:
- Java Debugger extension version:

##### Steps To Reproduce
1. [step 1]
2. [step 2]

[attach a sample project reproducing the error]
[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)

**Comment by Skermin8r** [comment]
I too was having this issue.  Found this in the 'Java Language Server Log':

Contains: Cannot extract bundle symbolicName or version c:\Users\ME\.vscode\extensions\vscjava.vscode-java-debug-0.56.2024021907\server\com.microsoft.java.debug.plugin-0.51.1.jar
java.nio.file.NoSuchFileException: c:\Users\ME\.vscode\extensions\vscjava.vscode-java-debug-0.56.2024021907\server\com.microsoft.java.debug.plugin-0.51.1.jar
	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.<init>(Unknown Source)
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.getBundleInfo(BundleUtils.java:328)
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.loadBundles(BundleUtils.java:120)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:109)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:64)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:284)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Found this in the directory:

C:\Users\ME\.vscode\extensions\vscjava.vscode-java-debug-0.56.2024021907\com.microsoft.java.debug.plugin-0.51.0.jar

Created a copy of THIS file and renamed it:

C:\Users\ME\.vscode\extensions\vscjava.vscode-java-debug-0.56.2024021907\com.microsoft.java.debug.plugin-0.51.1.jar

Restarted VScode and am now able to launch/debug Java code.
