### ISSUE TITLE
Cannot get Hot Code Replace to work - fullyQualifiedTypeName is null

### ISSUE THREAD

**Issue by Alexand3r** [microsoft/vscode-java-debug#1474]
##### Environment
- Operating System: Windows 11
- JDK version: 
openjdk 11.0.22 2024-01-16
OpenJDK Runtime Environment Temurin-11.0.22+7 (build 11.0.22+7)
OpenJDK 64-Bit Server VM Temurin-11.0.22+7 (build 11.0.22+7, mixed mode)
- Visual Studio Code version: 1.88.1
- Java extension version: v1.30.0
- Java Debugger extension version: v0.57.0

I have a multiproject Maven Springboot project, the debugger works as it should but the  Hot Code Replace does not work, when I press the button it says:

`Cannot find any changed classes for hot replace!`

And the error in the Java Output:

```
[Error - 9:35:33 AM] Apr 29, 2024, 9:35:33 AM Error in calling delegate command handler
Cannot invoke "String.split(String)" because "fullyQualifiedTypeName" is null
java.lang.NullPointerException: Cannot invoke "String.split(String)" because "fullyQualifiedTypeName" is null
	at com.microsoft.java.debug.plugin.internal.ResolveClasspathsHandler.getJavaProjectFromType(ResolveClasspathsHandler.java:117)
	at com.microsoft.java.debug.plugin.internal.Compile.compile(Compile.java:52)
	at com.microsoft.java.debug.plugin.internal.JavaDebugDelegateCommandHandler.executeCommand(JavaDebugDelegateCommandHandler.java:72)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:616)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
	
```

**Comment by testforstephen** [comment]
can you share a minimum sample project to help reproduce the issue?
