### ISSUE TITLE
NPE when start debugging.

### ISSUE THREAD

**Issue by tramchamploo** [Microsoft/vscode-java-debug#150]
```
[Error - 15:41:18] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at org.eclipse.jdt.ls.core.internal.text.correction.QuickAssistProcessor.getUniqueMethodName(QuickAssistProcessor.java:522)
	at org.eclipse.jdt.ls.core.internal.text.correction.QuickAssistProcessor.getExtractMethodProposal(QuickAssistProcessor.java:251)
	at org.eclipse.jdt.ls.core.internal.text.correction.QuickAssistProcessor.getAssists(QuickAssistProcessor.java:140)
	at org.eclipse.jdt.ls.core.internal.handlers.CodeActionHandler.getCodeActionCommands(CodeActionHandler.java:80)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$11(JDTLanguageServer.java:393)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 6 more
```
Then debugger says cannot find or load main class.

**Comment by akaroml** [comment]
Thanks for reporting this issue.  From the error message, this happened when you are performing some code action. Can you provide the steps to help us reproduce this issue?

Can you also let us know your configurations?
- Language Support for Java extension version
- Debugger for Java extension version
- OS version
- JDK version

**Comment by tramchamploo** [comment]
This is a really large maven project. And I just presssed F5 to debug a main method.
Language Support for Java extension version: 0.14.0
Debugger for java: 0.3.0
OS: macos 10.13.1
JDK: 1.8.0_152

**Comment by yaohaizh** [comment]
Fixed on the VSCode Java side.
