### ISSUE TITLE
PetClinic project: Could not find or load main class org.springframework.samples.petclinic.PetClinicApplication

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-java-debug#168]
##### Environment
- Operating System:  Win10(x64)
- JDK version:  9.0.1_64
- Visual Studio Code version:  1.18.1(64)
- Java extension version: 0.14.0
- Java Debugger extension version:  0.3.1

##### Steps To Reproduce

1. Open vscode and open spring-petclinic project
2. Start debug

[attach a sample project reproducing the error]
https://github.com/spring-projects/spring-petclinic 

[attach logs](https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#enable-logging)
Error: Could not find or load main class org.springframework.samples.petclinic.PetClinicApplication
Caused by: java.lang.ClassNotFoundException: org.springframework.samples.petclinic.PetClinicApplication
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getUrls(DefaultRestartInitializer.java:93)
	at org.springframework.boot.devtools.restart.DefaultRestartInitializer.getInitialUrls(DefaultRestartInitializer.java:56)
	at org.springframework.boot.devtools.restart.Restarter.<init>(Restarter.java:140)
	at org.springframework.boot.devtools.restart.Restarter.initialize(Restarter.java:546)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationStartingEvent(RestartApplicationListener.java:67)
	at org.springframework.boot.devtools.restart.RestartApplicationListener.onApplicationEvent(RestartApplicationListener.java:45)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)

##### Current Result
![image](https://user-images.githubusercontent.com/22470312/32940353-5f0321be-cbbd-11e7-936b-7e75ae405fd3.png)

**Comment by yaohaizh** [comment]
The Spring boot doesn't support JDK 9.0 yet until V2.l, what is the version of Spring framework here?

**Comment by bsaby** [comment]
The Spring Framework version here is lower than v2.1

**Comment by akaroml** [comment]
Version incompatibility issue which is not in our scope. Close for now.
