### ISSUE TITLE
HCR Got IOException from Virtual Machine

### ISSUE THREAD

**Issue by testforstephen** [Microsoft/vscode-java-debug#212]
```
[Error - 3:21:48 PM] Dec 21, 2017, 2:14:40 PM Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
Got IOException from Virtual Machine
com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
	at org.eclipse.jdi.internal.connect.PacketSendManager.sendPacket(PacketSendManager.java:90)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:187)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesBySignature(VirtualMachineImpl.java:652)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesByName(VirtualMachineImpl.java:682)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.getJdiClassesByName(JavaHotCodeReplaceProvider.java:408)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.filterNotLoadedTypes(JavaHotCodeReplaceProvider.java:385)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.doHotCodeReplace(JavaHotCodeReplaceProvider.java:332)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.resourceChanged(JavaHotCodeReplaceProvider.java:311)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Error - 3:23:16 PM] Dec 21, 2017, 2:14:40 PM Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
Got IOException from Virtual Machine
com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
	at org.eclipse.jdi.internal.connect.PacketSendManager.sendPacket(PacketSendManager.java:90)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:187)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesBySignature(VirtualMachineImpl.java:652)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesByName(VirtualMachineImpl.java:682)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.getJdiClassesByName(JavaHotCodeReplaceProvider.java:408)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.filterNotLoadedTypes(JavaHotCodeReplaceProvider.java:385)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.doHotCodeReplace(JavaHotCodeReplaceProvider.java:332)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.resourceChanged(JavaHotCodeReplaceProvider.java:311)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Error - 3:23:16 PM] Dec 21, 2017, 2:14:40 PM Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
Got IOException from Virtual Machine
com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
	at org.eclipse.jdi.internal.connect.PacketSendManager.sendPacket(PacketSendManager.java:90)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:187)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesBySignature(VirtualMachineImpl.java:652)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesByName(VirtualMachineImpl.java:682)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.getJdiClassesByName(JavaHotCodeReplaceProvider.java:408)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.filterNotLoadedTypes(JavaHotCodeReplaceProvider.java:385)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.doHotCodeReplace(JavaHotCodeReplaceProvider.java:332)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.resourceChanged(JavaHotCodeReplaceProvider.java:311)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Error - 3:23:24 PM] Dec 21, 2017, 2:14:40 PM Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
Got IOException from Virtual Machine
com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
	at org.eclipse.jdi.internal.connect.PacketSendManager.sendPacket(PacketSendManager.java:90)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:187)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesBySignature(VirtualMachineImpl.java:652)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesByName(VirtualMachineImpl.java:682)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.getJdiClassesByName(JavaHotCodeReplaceProvider.java:408)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.filterNotLoadedTypes(JavaHotCodeReplaceProvider.java:385)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.doHotCodeReplace(JavaHotCodeReplaceProvider.java:332)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.resourceChanged(JavaHotCodeReplaceProvider.java:311)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Error - 3:23:24 PM] Dec 21, 2017, 2:14:40 PM Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
Got IOException from Virtual Machine
com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
	at org.eclipse.jdi.internal.connect.PacketSendManager.sendPacket(PacketSendManager.java:90)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:187)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesBySignature(VirtualMachineImpl.java:652)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesByName(VirtualMachineImpl.java:682)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.getJdiClassesByName(JavaHotCodeReplaceProvider.java:408)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.filterNotLoadedTypes(JavaHotCodeReplaceProvider.java:385)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.doHotCodeReplace(JavaHotCodeReplaceProvider.java:332)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.resourceChanged(JavaHotCodeReplaceProvider.java:311)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Error - 3:23:35 PM] Dec 21, 2017, 2:14:40 PM Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
Got IOException from Virtual Machine
com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
	at org.eclipse.jdi.internal.connect.PacketSendManager.sendPacket(PacketSendManager.java:90)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:187)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesBySignature(VirtualMachineImpl.java:652)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesByName(VirtualMachineImpl.java:682)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.getJdiClassesByName(JavaHotCodeReplaceProvider.java:408)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.filterNotLoadedTypes(JavaHotCodeReplaceProvider.java:385)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.doHotCodeReplace(JavaHotCodeReplaceProvider.java:332)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.resourceChanged(JavaHotCodeReplaceProvider.java:311)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Error - 3:23:35 PM] Dec 21, 2017, 2:14:40 PM Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
Got IOException from Virtual Machine
com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
	at org.eclipse.jdi.internal.connect.PacketSendManager.sendPacket(PacketSendManager.java:90)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:187)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesBySignature(VirtualMachineImpl.java:652)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesByName(VirtualMachineImpl.java:682)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.getJdiClassesByName(JavaHotCodeReplaceProvider.java:408)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.filterNotLoadedTypes(JavaHotCodeReplaceProvider.java:385)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.doHotCodeReplace(JavaHotCodeReplaceProvider.java:332)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.resourceChanged(JavaHotCodeReplaceProvider.java:311)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Error - 3:24:16 PM] Dec 21, 2017, 2:14:40 PM Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
Got IOException from Virtual Machine
com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
	at org.eclipse.jdi.internal.connect.PacketSendManager.sendPacket(PacketSendManager.java:90)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:187)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesBySignature(VirtualMachineImpl.java:652)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesByName(VirtualMachineImpl.java:682)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.getJdiClassesByName(JavaHotCodeReplaceProvider.java:408)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.filterNotLoadedTypes(JavaHotCodeReplaceProvider.java:385)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.doHotCodeReplace(JavaHotCodeReplaceProvider.java:332)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.resourceChanged(JavaHotCodeReplaceProvider.java:311)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

[Error - 3:24:16 PM] Dec 21, 2017, 2:14:40 PM Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
Got IOException from Virtual Machine
com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
	at org.eclipse.jdi.internal.connect.PacketSendManager.sendPacket(PacketSendManager.java:90)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:187)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesBySignature(VirtualMachineImpl.java:652)
	at org.eclipse.jdi.internal.VirtualMachineImpl.classesByName(VirtualMachineImpl.java:682)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.getJdiClassesByName(JavaHotCodeReplaceProvider.java:408)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.filterNotLoadedTypes(JavaHotCodeReplaceProvider.java:385)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.doHotCodeReplace(JavaHotCodeReplaceProvider.java:332)
	at com.microsoft.java.debug.plugin.internal.JavaHotCodeReplaceProvider.resourceChanged(JavaHotCodeReplaceProvider.java:311)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:360)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by yaohaizh** [comment]
Fixed.
