### ISSUE TITLE
Java test runner doesn't resolve test dependencies

### ISSUE THREAD

**Issue by saard** [Microsoft/vscode-java-debug#276]
[provide a description of the issue]

##### Environment
Windows 10
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

- VS Code version: 1.22.2
- Language support for Java: 0.22.0
- Java extension pack version: 0.3.0
- Java Debugger extension version: 0.8.0
- Java test Runner extension version:  0.5.0
- Maven For Java extension version: 0.7.0

##### Steps To Reproduce

Run test which is using mockito 
import org.mockito.Mockito;

##### Current Result
java.lang.NoSuchMethodError: org.mockito.mock.MockCreationSettings.getSerializableMode()Lorg/mockito/mock/SerializableMode;
	at org.powermock.api.mockito.repackaged.AcrossJVMSerializationFeature.enableSerializationAcrossJVM(AcrossJVMSerializationFeature.java:166)
	at org.powermock.api.mockito.repackaged.CglibMockMaker.createMock(CglibMockMaker.java:23)
	at org.powermock.api.mockito.internal.mockmaker.PowerMockMaker.createMock(PowerMockMaker.java:45)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:26)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:51)
	at org.mockito.Mockito.mock(Mockito.java:1243)
	at org.mockito.Mockito.mock(Mockito.java:1120)
	at com.portal.site.v2.common.service.AbstractPortalSiteV2Test.<init>(AbstractPortalSiteV2Test.java:151)
	at com.portal.site.v2.common.service.AbstractPortalSiteV2MockTest.<init>(AbstractPortalSiteV2MockTest.java:47)
	at com.portal.site.v2.common.model.json.runtime.Wave9ToWave11ConverterTest.<init>(Wave9ToWave11ConverterTest.java:21)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.microsoft.java.test.runner.JUnit4TestReference.run(JUnit4TestReference.java:51)
	at com.microsoft.java.test.runner.CustomizedJUnitCoreRunner.run(CustomizedJUnitCoreRunner.java:45)
	at com.microsoft.java.test.runner.JUnitLauncher.main(JUnitLauncher.java:21)

##### Expected Result

running from command line maven works.
running using eclipse works.

**Comment by SummerSun** [comment]
Hi,

Thank you for reporting the issue. We are wondering, if you are working on a open source project, could you please provide us more about it? It will help a lot about the investigation. Otherwise, a sample project is good too.

**Comment by shivamju** [comment]
Hi ,

Are you able to resolve this issue.I am also stuck in similar problem.

**Comment by andxu** [comment]
Reopen this issue , @shivamju could you please provide the reproduce step
