### ISSUE TITLE
Failed to remote debug azure cloud services?

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/vscode-java-debug#450]
I'm having issue remote debugging.  

Any suggestion on what the issue could be?  Not sure if this is an issue with vscode vs. configuration.  I followed https://www.youtube.com/watch?v=n9nw6MPG0Vo which describe how to connect remotely.  

Thanks!

##### Environment
- Operating System: macOS Sierra Version 10.12.6
- JDK version:
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

- Visual Studio Code version: Version 1.27.2 (1.27.2)
- Java extension version: 0.4.0
- Java Debugger extension version: 0.13.0

##### Steps To Reproduce

Launch.json

```
{
    "version": "0.2.0",
    "configurations": [
      {
        "type": "java",
        "name": "Attach to Azure Function on the Cloud (Attach)",
        "request": "attach",
        "hostName": "localhost",
        "port": 8898
      }
    ]
  }
```
  

1. Deploy azure function to azure and make sure its running
2.  npm install --global cloud-debug-tools to install debug tool
3. Try to remote debug the azure function with:

```
$ dbgproxy <azure function url>
Function App:                <function name>
Subscription:                 <subscription>
Resource Group:           <resource>
Fetch debug settings:         done
Remote debugging is enabled on <azure function url>
[Server] listening on 127.0.0.1:8898
```

Note: the output verifies that the cloud service is running.  In this case the azure function.  It will print out all the info related to it.  When it's fully loaded it will output:

`Now you should be able to debug using "jdb -connect com.sun.jdi.SocketAttach:hostname=127.0.0.1,port=8898"`

In the launch.json in vscode, it's configured to port 8898 and localhost which is 127.0.0.1.  When i try to attach, I get the following error:

```
[Heartbeat] Running
[Server] client connected 127.0.0.1:60728
[WebSocket] client connected
[WebSocket] Error: write EPIPE
[WebSocket] connection closed
```

And vscode pops up:

![image](https://user-images.githubusercontent.com/16171726/46449236-bcd8ec00-c73f-11e8-991f-4104fd247794.png)

When I look at the vs code log for java, I see:

```
!ENTRY java-debug 4 0 2018-10-03 18:56:42.727
!MESSAGE [error response][attach]: Failed to attach to remote debuggee VM. Reason: com.sun.jdi.connect.spi.ClosedConnectionException
!STACK 0
com.microsoft.java.debug.core.DebugException: Failed to attach to remote debuggee VM. Reason: com.sun.jdi.connect.spi.ClosedConnectionException
    at com.microsoft.java.debug.core.adapter.AdapterUtils.createCompletionException(AdapterUtils.java:227)
    at com.microsoft.java.debug.core.adapter.handler.AttachRequestHandler.handle(AttachRequestHandler.java:82)
    at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:85)
    at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
    at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
    at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:84)
    at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
    at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.jdi.connect.spi.ClosedConnectionException
    at org.eclipse.jdi.internal.connect.SocketTransportService.readHandshake(SocketTransportService.java:225)
    at org.eclipse.jdi.internal.connect.SocketTransportService.access$1(SocketTransportService.java:216)
    at org.eclipse.jdi.internal.connect.SocketTransportService$3.run(SocketTransportService.java:185)
    ... 1 more
```

##### Current Result

Failed to attach to remote debuggee VM. Reason: com.sun.jdi.connect.spi.ClosedConnectionException

##### Expected Result

To remote connect to the service running on the cloud

**Comment by jdneo** [comment]
@darewreck54 The document is out of date. Currently, the java function could not remote debug.

There is a tracking issue here: https://github.com/Azure/azure-functions-host/issues/2986
