### ISSUE TITLE
Exception on threads request

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-debug#59]
[Error - 2:22:01 PM] Sep 26, 2017 2:12:02 PM DebugSession dispatch exception: com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
Got IOException from Virtual Machine
com.sun.jdi.VMDisconnectedException: Got IOException from Virtual Machine
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:186)
	at org.eclipse.jdi.internal.connect.PacketReceiveManager.getReply(PacketReceiveManager.java:204)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:192)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:227)
	at org.eclipse.jdi.internal.MirrorImpl.requestVM(MirrorImpl.java:243)
	at org.eclipse.jdi.internal.ThreadReferenceImpl.name(ThreadReferenceImpl.java:356)
	at com.microsoft.java.debug.core.adapter.handler.ThreadsRequestHandler.threads(ThreadsRequestHandler.java:79)
	at com.microsoft.java.debug.core.adapter.handler.ThreadsRequestHandler.handle(ThreadsRequestHandler.java:54)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:73)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:208)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.processData(ProtocolServer.java:177)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.start(ProtocolServer.java:99)
	at com.microsoft.java.debug.plugin.internal.JavaDebugServer$2.run(JavaDebugServer.java:139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by andxu** [comment]
https://github.com/Microsoft/java-debug/pull/67
