### ISSUE TITLE
"Model not available for ..." error on clicking Run or Debug

### ISSUE THREAD

**Issue by manastalukdar** [microsoft/vscode-java-debug#681]
When clicking Run or Debug, an error pops up saying "Model not available for ...".

##### Environment
- Operating System: Windows 10 x64
- JDK version: 13
- Visual Studio Code version: 1.39.0-insider
- Java extension version: 0.50
- Java Debugger extension version: 0.22

**Comment by testforstephen** [comment]
could you share the log file to us? Invoke command "Java: Open all log files"

**Comment by manastalukdar** [comment]
I have downgraded to JDK 12 until gradle (and vscode-java) fully support 13. If this issue still happens at that point, I will provide logs.

**Comment by erindru** [comment]
I am currently getting this on Java 11 right after upgrading to VSCode 1.39.1. Exiting and restarting VSCode can make it go away. I have attached the log files which show an exception from JDT.

[vscode-java-debug.log](https://github.com/microsoft/vscode-java-debug/files/3722002/vscode-java-debug.log)
[vscode-java-debug-client.log](https://github.com/microsoft/vscode-java-debug/files/3722004/vscode-java-debug-client.log)

It appears to relate to Gradle support:

```
!ENTRY org.eclipse.jdt.ls.core 4 2 2019-10-14 06:04:00.450
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
!STACK 0
org.eclipse.buildship.core.internal.GradlePluginsRuntimeException: Model not available for qty-api
	at org.eclipse.buildship.core.internal.workspace.GradleClasspathContainerRuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(GradleClasspathContainerRuntimeClasspathEntryResolver.java:76)
	at org.eclipse.buildship.core.internal.workspace.GradleClasspathContainerRuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(GradleClasspathContainerRuntimeClasspathEntryResolver.java:55)
	at org.eclipse.jdt.internal.launching.RuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(RuntimeClasspathEntryResolver.java:49)
	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspathEntry(JavaRuntime.java:1268)
	at org.eclipse.buildship.core.internal.launch.GradleClasspathProvider.resolveClasspath(GradleClasspathProvider.java:100)
	at org.eclipse.jdt.internal.launching.RuntimeClasspathProvider.resolveClasspath(RuntimeClasspathProvider.java:68)
	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspath(JavaRuntime.java:1659)
	at com.microsoft.java.debug.plugin.internal.ResolveClasspathsHandler.computeClassPath(ResolveClasspathsHandler.java:206)
	at com.microsoft.java.debug.plugin.internal.ResolveClasspathsHandler.computeClassPath(ResolveClasspathsHandler.java:185)
	at com.microsoft.java.debug.plugin.internal.ResolveClasspathsHandler.resolveClasspaths(ResolveClasspathsHandler.java:73)
	at com.microsoft.java.debug.plugin.internal.JavaDebugDelegateCommandHandler.executeCommand(JavaDebugDelegateCommandHandler.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:213)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:203)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:463)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$45(JDTLanguageServer.java:936)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by mapio** [comment]
I've VScode 1.39.2 and Oracle JDK 11… same error as @erindu. And in my case there is no way to fix it.

**Comment by testforstephen** [comment]
could you mind sharing us a sample project to reproduce this issue?

**Comment by mapio** [comment]
I would, if I could. But I was so desperate that I erased my `~/.vscode` dir and reinstalled the minimal number of extensions required for Java. Now it is gone… I suspect one of the extensions I added to my bloated past configuration was the culprit…

**Comment by jmullo** [comment]
I'm getting this error whenever a breakpoint is hit. Stepping or continuing does not work:

`[Error - 11.55.50] 5.11.2019 11:55:50 [error response][next]: Failed to step because the thread 'Attach Listener' is not suspended in the target VM.
Failed to step because the thread 'Attach Listener' is not suspended in the target VM.
com.microsoft.java.debug.core.DebugException: Failed to step because the thread 'Attach Listener' is not suspended in the target VM.`

Java 8.

**Comment by testforstephen** [comment]
@jmullo Looks like you're stepping a running thread, that's not supported. Only paused thread is allowed to step over. 

Could you enable the debug log via adding the user setting `java.debug.logLevel` to `verbose`,  try again, and then share the log file? 

Here is the command to get the log file:
**F1** -> **Open Java language server log file**

**Comment by jmullo** [comment]
@testforstephen The problem was resolved for now by deleting all temporary build files and cleaning Java language server workspace. Will share the log if it occurs again.
