### ISSUE TITLE
Launch fails when terminal is set to cmd

### ISSUE THREAD

**Issue by astrelsky** [microsoft/vscode-java-debug#738]
Attempting to launch a debug session which defines `-Djava.system.class.loader` fails to start only when `"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe"` is set. I have copied the launch arguments from the vscode terminal and ran through the cmd prompt (minus the `-agentlib` and `vscjava.vscode-java-debug-0.24.0\scripts\launcher.bat`) and it launched without a problem.

##### Environment
![env](https://user-images.githubusercontent.com/46897303/71451498-2e39fb80-2745-11ea-8bc9-2e74e2ffba00.PNG)

- JDK version: 13.0.1
- Java extension version: 0.55.1
- Java Debugger extension version: 0.24.0

##### Steps To Reproduce
1. Set `"terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe"` in the workspace settings
2. Launch and hopefully the issue is reproduced.
3. If not I can attach a sample project that uses the same classloader, but it'll require a ghidra installation.

[-1577316535668.log](https://github.com/microsoft/vscode-java-debug/files/4000901/-1577316535668.log)
[java-ls.log](https://github.com/microsoft/vscode-java-debug/files/4000902/java-ls.log)

##### Current Result
vscode-java launches via **powershell** and fails.

##### Expected Result
Launch via **cmd** as per the settings and launch successfully.

##### Additional Informations
This is a nuisance because having to watch 1000+ System.ArgumentOutOfRangeException reports from PSReadLine is quite a grievance. More details on that [here](https://github.com/PowerShell/PSReadLine/issues/292)

**Comment by testforstephen** [comment]
I can reproduce this issue in the insider version. This is an issue with the upstream vscode insider version. See https://github.com/microsoft/vscode/issues/87700

Current workaround:
- Add `"java.debug.settings.console": "internalConsole"` to your user setting. Use debug console to run your program.
- This works in the official stable VS Code 1.41.1. Try that.

**Comment by astrelsky** [comment]
> I can reproduce this issue in the insider version. This is an issue with the upstream vscode insider version. See [microsoft/vscode#87700](https://github.com/microsoft/vscode/issues/87700)
> 
> Current workaround:
> 
> * Add `"java.debug.settings.console": "internalConsole"` to your user setting. Use debug console to run your program.
> * Change your integrated terminal to powershell directly, it works.

I see I didn't realize the issue was the insiders build itself.

@testforstephen is the PSReadLine issue a powershell issue, vscode issue, or vscode-debug issue? It's quite annoying to watch this fill the terminal everytime I launch something in the internal console.
<details><summary>Exceptions</summary>

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine> & 'C:\Users\astre\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.24.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-13.0.1\bin\java' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:51423' '-Djava.system.class.loader=ghidra.GhidraClassLoader' '-Declipse.project.dir=C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine' '-Dpython.console.encoding=UTF-8' '-Dfile.encoding=UTF8' '-Dlog4j.configuration=C:\Users\astre\Documents\ghidra_9.2_DEV/support/debug.log4j.xml' '-Dlog4j.skipJansi=true' '-Duser.country=US' '-Duser.language=en' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dvisualvm.display.name=Ghidra' '-Dfile.encoding=UTF-8' '@C:\Users\astre\AppData\Local\Temp\cp_45cu2016fa71ovk0uojnbxo9l.argfile' 'ghidra.GhidraLauncher' 'ghidra.Gh
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 D s u n . e r r . e n c o d i n g = U T F - 8 ' Space ' - D v i s u a l v m . d i s p l a y . n a m e = G h i d r a ' Space 
' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' @ C : \ U s e r s \ a s t r e \ A p p D a t a \ L o c a l \ T e m p \ c p _ 4 5 c u 2 0 1 6 f a 7 1 o v k 0 u o j n b x o 9 l . a r g f i l e ' Space ' g h i d r a . G h i d r a L a u n c h e r ' 
Space ' g h i d r a . G h i d r a R u n ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine> & 'C:\Users\astre\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.24.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-13.0.1\bin\java' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:51423' '-Djava.system.class.loader=ghidra.GhidraClassLoader' '-Declipse.project.dir=C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine' '-Dpython.console.encoding=UTF-8' '-Dfile.encoding=UTF8' '-Dlog4j.configuration=C:\Users\astre\Documents\ghidra_9.2_DEV/support/debug.log4j.xml' '-Dlog4j.skipJansi=true' '-Duser.country=US' '-Duser.language=en' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dvisualvm.display.name=Ghidra' '-Dfile.encoding=UTF-8' '@C:\Users\astre\AppData\Local\Temp\cp_45cu2016fa71ovk0uojnbxo9l.argfile' 'ghidra.GhidraLauncher' 'ghidra.Ghi
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 D s u n . e r r . e n c o d i n g = U T F - 8 ' Space ' - D v i s u a l v m . d i s p l a y . n a m e = G h i d r a ' Space 
' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' @ C : \ U s e r s \ a s t r e \ A p p D a t a \ L o c a l \ T e m p \ c p _ 4 5 c u 2 0 1 6 f a 7 1 o v k 0 u o j n b x o 9 l . a r g f i l e ' Space ' g h i d r a . G h i d r a L a u n c h e r ' 
Space ' g h i d r a . G h i d r a R u n ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine> & 'C:\Users\astre\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.24.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-13.0.1\bin\java' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:51423' '-Djava.system.class.loader=ghidra.GhidraClassLoader' '-Declipse.project.dir=C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine' '-Dpython.console.encoding=UTF-8' '-Dfile.encoding=UTF8' '-Dlog4j.configuration=C:\Users\astre\Documents\ghidra_9.2_DEV/support/debug.log4j.xml' '-Dlog4j.skipJansi=true' '-Duser.country=US' '-Duser.language=en' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dvisualvm.display.name=Ghidra' '-Dfile.encoding=UTF-8' '@C:\Users\astre\AppData\Local\Temp\cp_45cu2016fa71ovk0uojnbxo9l.argfile' 'ghidra.GhidraLauncher' 'ghidra.Ghid
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 D s u n . e r r . e n c o d i n g = U T F - 8 ' Space ' - D v i s u a l v m . d i s p l a y . n a m e = G h i d r a ' Space 
' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' @ C : \ U s e r s \ a s t r e \ A p p D a t a \ L o c a l \ T e m p \ c p _ 4 5 c u 2 0 1 6 f a 7 1 o v k 0 u o j n b x o 9 l . a r g f i l e ' Space ' g h i d r a . G h i d r a L a u n c h e r ' 
Space ' g h i d r a . G h i d r a R u n ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine> & 'C:\Users\astre\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.24.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-13.0.1\bin\java' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:51423' '-Djava.system.class.loader=ghidra.GhidraClassLoader' '-Declipse.project.dir=C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine' '-Dpython.console.encoding=UTF-8' '-Dfile.encoding=UTF8' '-Dlog4j.configuration=C:\Users\astre\Documents\ghidra_9.2_DEV/support/debug.log4j.xml' '-Dlog4j.skipJansi=true' '-Duser.country=US' '-Duser.language=en' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dvisualvm.display.name=Ghidra' '-Dfile.encoding=UTF-8' '@C:\Users\astre\AppData\Local\Temp\cp_45cu2016fa71ovk0uojnbxo9l.argfile' 'ghidra.GhidraLauncher' 'ghidra.Ghidr
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 D s u n . e r r . e n c o d i n g = U T F - 8 ' Space ' - D v i s u a l v m . d i s p l a y . n a m e = G h i d r a ' Space 
' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' @ C : \ U s e r s \ a s t r e \ A p p D a t a \ L o c a l \ T e m p \ c p _ 4 5 c u 2 0 1 6 f a 7 1 o v k 0 u o j n b x o 9 l . a r g f i l e ' Space ' g h i d r a . G h i d r a L a u n c h e r ' 
Space ' g h i d r a . G h i d r a R u n ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine> & 'C:\Users\astre\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.24.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-13.0.1\bin\java' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:51423' '-Djava.system.class.loader=ghidra.GhidraClassLoader' '-Declipse.project.dir=C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine' '-Dpython.console.encoding=UTF-8' '-Dfile.encoding=UTF8' '-Dlog4j.configuration=C:\Users\astre\Documents\ghidra_9.2_DEV/support/debug.log4j.xml' '-Dlog4j.skipJansi=true' '-Duser.country=US' '-Duser.language=en' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dvisualvm.display.name=Ghidra' '-Dfile.encoding=UTF-8' '@C:\Users\astre\AppData\Local\Temp\cp_45cu2016fa71ovk0uojnbxo9l.argfile' 'ghidra.GhidraLauncher' 'ghidra.Ghidra
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 D s u n . e r r . e n c o d i n g = U T F - 8 ' Space ' - D v i s u a l v m . d i s p l a y . n a m e = G h i d r a ' Space 
' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' @ C : \ U s e r s \ a s t r e \ A p p D a t a \ L o c a l \ T e m p \ c p _ 4 5 c u 2 0 1 6 f a 7 1 o v k 0 u o j n b x o 9 l . a r g f i l e ' Space ' g h i d r a . G h i d r a L a u n c h e r ' 
Space ' g h i d r a . G h i d r a R u n ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine> & 'C:\Users\astre\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.24.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-13.0.1\bin\java' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:51423' '-Djava.system.class.loader=ghidra.GhidraClassLoader' '-Declipse.project.dir=C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine' '-Dpython.console.encoding=UTF-8' '-Dfile.encoding=UTF8' '-Dlog4j.configuration=C:\Users\astre\Documents\ghidra_9.2_DEV/support/debug.log4j.xml' '-Dlog4j.skipJansi=true' '-Duser.country=US' '-Duser.language=en' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dvisualvm.display.name=Ghidra' '-Dfile.encoding=UTF-8' '@C:\Users\astre\AppData\Local\Temp\cp_45cu2016fa71ovk0uojnbxo9l.argfile' 'ghidra.GhidraLauncher' 'ghidra.GhidraR
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 D s u n . e r r . e n c o d i n g = U T F - 8 ' Space ' - D v i s u a l v m . d i s p l a y . n a m e = G h i d r a ' Space 
' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' @ C : \ U s e r s \ a s t r e \ A p p D a t a \ L o c a l \ T e m p \ c p _ 4 5 c u 2 0 1 6 f a 7 1 o v k 0 u o j n b x o 9 l . a r g f i l e ' Space ' g h i d r a . G h i d r a L a u n c h e r ' 
Space ' g h i d r a . G h i d r a R u n ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine> & 'C:\Users\astre\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.24.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-13.0.1\bin\java' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:51423' '-Djava.system.class.loader=ghidra.GhidraClassLoader' '-Declipse.project.dir=C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine' '-Dpython.console.encoding=UTF-8' '-Dfile.encoding=UTF8' '-Dlog4j.configuration=C:\Users\astre\Documents\ghidra_9.2_DEV/support/debug.log4j.xml' '-Dlog4j.skipJansi=true' '-Duser.country=US' '-Duser.language=en' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dvisualvm.display.name=Ghidra' '-Dfile.encoding=UTF-8' '@C:\Users\astre\AppData\Local\Temp\cp_45cu2016fa71ovk0uojnbxo9l.argfile' 'ghidra.GhidraLauncher' 'ghidra.GhidraRu
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 D s u n . e r r . e n c o d i n g = U T F - 8 ' Space ' - D v i s u a l v m . d i s p l a y . n a m e = G h i d r a ' Space 
' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' @ C : \ U s e r s \ a s t r e \ A p p D a t a \ L o c a l \ T e m p \ c p _ 4 5 c u 2 0 1 6 f a 7 1 o v k 0 u o j n b x o 9 l . a r g f i l e ' Space ' g h i d r a . G h i d r a L a u n c h e r ' 
Space ' g h i d r a . G h i d r a R u n ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine> & 'C:\Users\astre\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.24.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-13.0.1\bin\java' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:51423' '-Djava.system.class.loader=ghidra.GhidraClassLoader' '-Declipse.project.dir=C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine' '-Dpython.console.encoding=UTF-8' '-Dfile.encoding=UTF8' '-Dlog4j.configuration=C:\Users\astre\Documents\ghidra_9.2_DEV/support/debug.log4j.xml' '-Dlog4j.skipJansi=true' '-Duser.country=US' '-Duser.language=en' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dvisualvm.display.name=Ghidra' '-Dfile.encoding=UTF-8' '@C:\Users\astre\AppData\Local\Temp\cp_45cu2016fa71ovk0uojnbxo9l.argfile' 'ghidra.GhidraLauncher' 'ghidra.GhidraRun
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 D s u n . e r r . e n c o d i n g = U T F - 8 ' Space ' - D v i s u a l v m . d i s p l a y . n a m e = G h i d r a ' Space 
' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' @ C : \ U s e r s \ a s t r e \ A p p D a t a \ L o c a l \ T e m p \ c p _ 4 5 c u 2 0 1 6 f a 7 1 o v k 0 u o j n b x o 9 l . a r g f i l e ' Space ' g h i d r a . G h i d r a L a u n c h e r ' 
Space ' g h i d r a . G h i d r a R u n ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine> & 'C:\Users\astre\.vscode-insiders\extensions\vscjava.vscode-java-debug-0.24.0\scripts\launcher.bat' 'C:\Program Files\Java\jdk-13.0.1\bin\java' '-agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:51423' '-Djava.system.class.loader=ghidra.GhidraClassLoader' '-Declipse.project.dir=C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine' '-Dpython.console.encoding=UTF-8' '-Dfile.encoding=UTF8' '-Dlog4j.configuration=C:\Users\astre\Documents\ghidra_9.2_DEV/support/debug.log4j.xml' '-Dlog4j.skipJansi=true' '-Duser.country=US' '-Duser.language=en' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dvisualvm.display.name=Ghidra' '-Dfile.encoding=UTF-8' '@C:\Users\astre\AppData\Local\Temp\cp_45cu2016fa71ovk0uojnbxo9l.argfile' 'ghidra.GhidraLauncher' 'ghidra.GhidraRun'
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/lzybkr/PSReadLine/issues/new
-----------------------------------------------------------------------
Last 200 Keys:
 D s u n . e r r . e n c o d i n g = U T F - 8 ' Space ' - D v i s u a l v m . d i s p l a y . n a m e = G h i d r a ' Space 
' - D f i l e . e n c o d i n g = U T F - 8 ' Space ' @ C : \ U s e r s \ a s t r e \ A p p D a t a \ L o c a l \ T e m p \ c p _ 4 5 c u 2 0 1 6 f a 7 1 o v k 0 u o j n b x o 9 l . a r g f i l e ' Space ' g h i d r a . G h i d r a L a u n c h e r ' 
Space ' g h i d r a . G h i d r a R u n ' Space Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -1.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
-----------------------------------------------------------------------
PS C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine> & 'C:\Users\astre\.vscode-insidedwp=transport=dt_socket,server=n,suspend=y,address=localhost:51423' '-Djava.system.class.loader=ghidra.GhidraClassLoader' '-Declipse.project.dir=C:\Users\astre\Documents\ghidra_plugins\ghidra-emotionengine\custom\ghidra-emotionengine' '-Dpython.console.encoding=UTF-8' '-Dfile.encoding=UTF8' '-Dlog4j.configuration=C:\Users\astre\Documents\ghidra_9.2_DEV/support/debug.log4j.xml' '-Dlog4j.skipJansi=true' '-Duser.country=US' '-Duser.language=en' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dvisualvm.display.name=Ghidra' '-Dfile.encoding=UTF-8' '@C:\Users\astre\AppData\Local\Temp\cp_45cu2016fa71ovk0uojnbxo9l.argfile' 'ghidra.GhidraLauncher' 'ghidra.GhidraRun' 
Java HotSpot(TM) 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "ghidra.GhidraClassLoader"). To use archived non-system classes, this property must not be set
INFO  Using log config file: file:/C:/Users/astre/Documents/ghidra_9.2_DEV/support/debug.log4j.xml  (LoggingInitialization.java:59)
INFO  Using log file: C:\Users\astre\.ghidra\.ghidra_9.2_DEV\application.log  (LoggingInitialization.java:60) 
INFO  Loading user preferences: C:\Users\astre\.ghidra\.ghidra_9.2_DEV\preferences  (Preferences.java:122) 
DEBUG Unable to find splash screen text from: splash.txt  (InfoPanel.java:256) 
INFO  Class search complete (2319 ms)  (ClassSearcher.java:264) 
INFO  Initializing SSL Context  (SSLContextInitializer.java:83) 
INFO  Initializing Random Number Generator...  (SecureRandomFactory.java:37) 
INFO  Random Number Generator initialization complete: SHA1PRNG  (SecureRandomFactory.java:41)
INFO  Trust manager disabled, cacerts have not been set  (ApplicationTrustManagerFactory.java:95) 
INFO  User astre started Ghidra.  (GhidraRun.java:81) 
DEBUG Recovery snapshot timer set to 5 minute(s)  (RecoverySnapshotMgrPlugin.java:170) 
INFO  Opening project: C:\Users\astre\Documents\ps2_debug  (DefaultProject.java:134) 
INFO  Removed old presave file: C:\Users\astre\Documents\ps2_debug.rep\idata\44\~0000044e.db\tmp2204329498646548561.ps  (LocalBufferFile.java:1520)
```
</details>

**Comment by testforstephen** [comment]
It's just a VS Code bug, it passed the cmd-style command line arguments to powershell by mistake. insider is the nightly build of vscode, so regression is acceptable there. Please track the progress in the upstream issue.

**Comment by astrelsky** [comment]
> It's just a VS Code bug, it passed the cmd-style command line arguments to powershell by mistake. insider is the nightly build of vscode, so regression is acceptable there. Please track the progress in the upstream issue.

OH! I had to re-read that several times. So it is passing cmd-line args to powershell AND powershell args to cmd. Now it makes sense. I didn't realize they were the same and wanted to know where it should be reported. Thank you!
