### ISSUE TITLE
Failed to get variables. Reason: com.sun.jdi.InvalidStackFrameException

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/vscode-java-debug#767]
The locals are not loading in the debugger (in this case, not always).

##### Environment
- Operating System: Win10
- JDK version: 
- Visual Studio Code version: 1.41.1
- Java extension version: 0.55.1
- Java Debugger extension version: 0.24.0

##### Steps To Reproduce

[sample project reproducing the error](https://github.com/spottedmahn/experiments-2020/tree/master/failed-to-get-variables)

##### demo of problem

![failed-to-get-variables-repro-steps](https://user-images.githubusercontent.com/14079228/75360035-36b4cc80-5883-11ea-9cd4-c6e0e0442fa4.gif)

1. Debug the test
1. Put a breakpoint on `when(restHighLevelClient.indexAsync(any(), any(), any()))`
1. After the breakpoint is hit, enable Caught Exceptions
1. F5
1. Wait for the exception, inspect the debugger window

[java-lang-server.log](https://github.com/microsoft/vscode-java-debug/files/4256577/java-lang-server.log)

##### Current Result
![image](https://user-images.githubusercontent.com/14079228/75359806-eb9ab980-5882-11ea-90b7-01e4df664df4.png)

##### Expected Result
Variables to load

##### Exception from Java Server Log

>!ENTRY java-debug 4 0 2020-02-26 10:06:40.711
!MESSAGE [error response][variables]: Failed to get variables. Reason: com.sun.jdi.InvalidStackFrameException
!STACK 0
com.microsoft.java.debug.core.DebugException: Failed to get variables. Reason: com.sun.jdi.InvalidStackFrameException
	at com.microsoft.java.debug.core.adapter.AdapterUtils.createCompletionException(AdapterUtils.java:255)
	at com.microsoft.java.debug.core.adapter.handler.VariablesRequestHandler.handle(VariablesRequestHandler.java:118)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:87)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:86)
	at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
	at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.sun.jdi.InvalidStackFrameException
	at org.eclipse.jdi.internal.MirrorImpl.defaultReplyErrorHandler(MirrorImpl.java:294)
	at org.eclipse.jdi.internal.StackFrameImpl.getValues(StackFrameImpl.java:142)
	at org.eclipse.jdi.internal.StackFrameImpl.getValue(StackFrameImpl.java:78)
	at com.microsoft.java.debug.core.adapter.variables.VariableUtils.listLocalVariables(VariableUtils.java:153)
	at com.microsoft.java.debug.core.adapter.handler.VariablesRequestHandler.handle(VariablesRequestHandler.java:109)
	... 16 more

**Comment by holywar20** [comment]
Having the same issue. It's not clear what needs to be done to resolve it or even how to approach it.

**Comment by c3r38r170** [comment]
I have the same error too, if it's of use I could attach my error log but that error manifestation doesn't seem any different from mine.

**Comment by theloneflaneur** [comment]
Facing the same issue while using scanner

**Comment by robinchrist** [comment]
I'm getting the same errors.

Any ideas on this?

**Comment by testforstephen** [comment]
This issue only happens at the exception breakpoint. Because when it's exception breakpoint, the debugger will also show the exception toString message with a red dialog, and this operation will cause the target thread resumed and the cached stack frame to be invalid.

It will be fixed in the new release.
