### ISSUE TITLE
java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by tripathi-abhishek** [microsoft/vscode-java-debug#859]
Unable to run or debug against java files. Seems like vscode is compiling with one version and running with another.

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Codechef has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

##### Environment
- Operating System:  Win 10 Pro build 19041.388

- JDK version: 
---> PS C:\Users\ABHISHEK\Java_Projects> java -version
                        java version "1.8.0_261"
                        Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
                        Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
                        
                        --> PS C:\Users\ABHISHEK\Java_Projects> javac -version
                        javac 12.0.2

- Visual Studio Code version:  Version: 1.47.3 (user setup)
                                                  Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
                                                 Date: 2020-07-23T13:12:49.994Z
                                                 Electron: 7.3.2
                                                Chrome: 78.0.3904.130
                                                Node.js: 12.8.1
                                               V8: 7.8.279.23-electron.0
                                               OS: Windows_NT x64 10.0.19041

- Java extension version:  redhat.java@v0.9.1
                                         vscjava.vscode-java-pack@v0.9.1
                                         vscjava.vscode-maven@v0.23.0
                                          vscjava.vscode-java-test@v0.24.0
                                         vscjava.vscode-java-dependency@v0.10.2
                                          vscjava.vscode-java-debug@v0.27.1

- Java Debugger extension version: v0.27.1

##### Steps To Reproduce
1. Install JDK
2. Install VSCode
3. Add Java Extension Pack
4. Write simple HelloWorld java file
5. Run Debug

```
public class HelloWorld {
  public static void main(String[] args) {
    System.out.println("Hello, world");
  }
}
```

##### Current Result

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: Codechef has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

##### Expected Result

`Hello, world`

##### Additional Informations

Tried installing and reinstalling the extension several times but no use.
Tried the solution suggested by @brightzheng100  --> [https://github.com/microsoft/vscode-java-debug/issues/555#issuecomment-581843924]
but that did not work at all.

**Comment by testforstephen** [comment]
> java -version
java version "1.8.0_261"

> javac -version
javac 12.0.2

Can you explain why java and javac don't point to the same version?

**Comment by tripathi-abhishek** [comment]
Sorry but i donno myself. Can you wxplain why?! I will try my best to sort it out.

**Comment by testforstephen** [comment]
Looks like JDK is not installed well in your environment. Would you mind sharing your VS Code user setting?

**Comment by tripathi-abhishek** [comment]
Thanks i made some changes and now env is all right.
Versions are correct but now the code is running yet no showing any output.

**Comment by tripathi-abhishek** [comment]
Solution to this problem : https://stackoverflow.com/questions/25074017/java-version-and-javac-version-showing-different-versions/55482621#55482621

Use the 2nd answer by @Dhananjay Yelwande
