### ISSUE TITLE
Unable to debug with the correct Java version

### ISSUE THREAD

**Issue by basecell** [microsoft/vscode-java-debug#873]
I have a vertx project, It is based on JDK 1.8, My machine has JDK1.8 and JDK11 installed. To use the latest Java plug-in, I set the `Java.home` option of the Java plug-in to the JDK11 installation directory, and the `java_home` in my system environment variable is still set to the JDK8 installation directory. My vscode settings are as follows:
```json
    "java.home": "C:\\Program Files\\AdoptOpenJDK\\jdk-11.0.8.10-hotspot",
    "java.configuration.runtimes": [
        {
            "name": "JavaSE-1.8",
            "path": "C:\\Program Files\\AdoptOpenJDK\\jdk-8.0.265.01-hotspot",
            "default": true
        }
    ]
```

##### Environment
- Operating System: Windows 10
- JDK version: openjdk version "1.8.0_265"
- Visual Studio Code version: 1.48.2
- Java extension version: v0.65.0
- Java Debugger extension version: v0.28.0

##### Steps To Reproduce
1. Open a vertx project base on JDK 1.8
2. Add `launch.json`, like this:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug Vert.x",
            "request": "launch",
            "mainClass": "io.vertx.core.Launcher",
            "args": "run com.myproject.microservice.MainVerticle -conf ${workspaceFolder}/myconfig/config.json",
        }
    ]
}
```
3. Run `Debug Vert.x`

Here is the command to start DEBUG:
```log
C:\Users\Admin\Desktop\myvertxproject> cd c:\Users\Admin\Desktop\myvertxproject && c:\Users\Admin\.vscode\extensions\vscjava.vscode-java-debug-0.28.0\scripts\launcher.bat "C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot\bin\java.exe" -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:56776 -Dfile.encoding=UTF-8 @C:\Users\Admin\AppData\Local\Temp\cp_8of7e7axsi6p6pjqtzeqqpfu5.argfile io.vertx.core.Launcher run com.myproject.microservice.MainVerticle -conf C:\Users\Admin\Desktop\myvertxproject/myconfig/config.json
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/C:/Maven-Repositories/io/netty/netty-common/4.1.19.Final/netty-common-4.1.19.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.ClassNotFoundException: com.myproject.microservice.MainVerticle
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
        at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:229)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:202)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:171)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:143)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:131)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
        at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
        at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:397)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
        at io.vertx.core.Launcher.main(Launcher.java:45)
8月 27, 2020 5:57:05 下午 io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
严重: Failed in deploying verticle
java.lang.ClassNotFoundException: com.myproject.microservice.MainVerticle
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
        at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:229)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:202)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:171)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:143)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:131)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
        at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
        at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:397)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
        at io.vertx.core.Launcher.main(Launcher.java:45)

java.lang.ClassNotFoundException: com.myproject.microservice.MainVerticle
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:37)
        at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:229)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:202)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:79)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:171)
        at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:143)
        at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:131)
        at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
        at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:42)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:159)
        at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:397)
        at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:270)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:226)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
        at io.vertx.core.Launcher.main(Launcher.java:45)
```
As you can see, it started debugging using JDK11, but this was incorrect!! so my project debugging failed. And after I rolled back the Java plug-in to v0.64.1 version, I can debug successfully.

##### Current Result
My project was based on JDK8, but was debugged using JDK11

##### Expected Result
I hope the debugger can use the corresponding JDK according to my project

##### Additional Informations
Help me, please!!

**Comment by testforstephen** [comment]
The debugger determines the runtime JDK based on your project's language level. Configured two JDKs in the user setting is the first step, then you should check your project's actual language level.

Could you open a Java file, hover at the icon below and share what it displays? 
![image](https://user-images.githubusercontent.com/14052197/90472455-2525f080-e153-11ea-984e-93f5146bbb67.png)

**Comment by basecell** [comment]
> The debugger determines the runtime JDK based on your project's language level. Configured two JDKs in the user setting is the first step, then you should check your project's actual language level.
> 
> Could you open a Java file, hover at the icon below and share what it displays?
> ![image](https://user-images.githubusercontent.com/14052197/90472455-2525f080-e153-11ea-984e-93f5146bbb67.png)

Thanks for the tip, I rechecked my `java.configuration.runtimes` configuration, It was found that the `path` was not really set to the JDK1.8 installation directory. There is a visually imperceptible difference in the space, I fixed the problem and it works now.
