### ISSUE TITLE
Running the contributed command: 'java.execute.workspaceCommand' failed.

### ISSUE THREAD

**Issue by Sunspawn** [microsoft/vscode-java-debug#950]
I cannot run any code after installing the java extensions in the ide. Manually compiling with javac and running the resulting .class file works just fine and dandy.

##### Environment
- Operating System: Windows 10
- JDK version: OpenJDK 15.0.2.7
- Visual Studio Code version: 1.53.2
- Java extension version: Language Support for java by red hat v0.75.0
- Java Debugger extension version: v0.31.0

##### Steps To Reproduce
I followed this: https://code.visualstudio.com/docs/java/java-tutorial up to the "Run the program" step in the 'Getting Started' doc in the ide itself and got the rror.

Literally copypasted the QuickStart class from the 'Getting Started' document in the ide.

##### Current Result

Nothing happens and I get the error "Running the contributed command: 'java.execute.workspaceCommand' failed."

##### Expected Result

The sample code should run.

**Comment by testforstephen** [comment]
Could you reload the VS Code window and try again?

**Comment by sangramsingha** [comment]
I got same issue after updating to version 0.77.0 of Language Support for Java(TM) by Red Hat (redhat.java) on VS codium

```
[2021-04-17 12:31:19.473] [renderer1] [error] Running the contributed command: 'java.execute.workspaceCommand' failed.: Error: Running the contributed command: 'java.execute.workspaceCommand' failed.
    at S._executeContributedCommand (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106930)
    at M.provideCompletionItems (/usr/share/codium/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:170847)
```

**Comment by testforstephen** [comment]
Please share your logs.

Output window:
**Language Support for Java**

Logs:
**F1 -> Java: Open All Log Files**

Dev Tools Console:
**Help -> Toggle Developer Tools -> Console**

**Comment by JohnTheBeloved** [comment]
`
Error: Running the contributed command: 'java.execute.workspaceCommand' failed.
	at S._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106930)
	at async Object.syncServer (/Users/john.alade/.vscode/extensions/shengchen.vscode-checkstyle-1.4.0/dist/extension.js:1:81077)
	at async Object.refresh (/Users/john.alade/.vscode/extensions/shengchen.vscode-checkstyle-1.4.0/dist/extension.js:1:79786)
	at async Object.initialize (/Users/john.alade/.vscode/extensions/shengchen.vscode-checkstyle-1.4.0/dist/extension.js:1:77932)
	at async g (/Users/john.alade/.vscode/extensions/shengchen.vscode-checkstyle-1.4.0/dist/extension.js:29:20243)
Error: Running the contributed command: 'java.execute.workspaceCommand' failed.
	at new AppInsightsAsyncCorrelatedErrorWrapper (/Users/john.alade/.vscode/extensions/qub.qub-xml-vscode-1.2.8/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:172:18)
	at S._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106930)

`

**Comment by KJNoonan** [comment]
I too am getting this error. For those looking for a work around reverting back to version 0.77 the command works again.

Attached are my logs. 
[vscodelogs.zip](https://github.com/microsoft/vscode-java-debug/files/6421884/vscodelogs.zip)

**Comment by testforstephen** [comment]
@JohnTheBeloved The exception you pasted is from shengchen.vscode-checkstyle extension, not related with Java debugger extension.

@KJNoonan I searched the keyword 'java.execute.workspaceCommand' in your logs, didn't find anything.

**Comment by eakst7** [comment]
I'm seeing the same problem with version 0.79.0 and 0.79.1 of the "Language Support for Java" extension.  Version 0.77 and 0.78 of the extension are fine.

Nothing relevant in the Language Support for Java output window or the Java log files.

The DevTools console, however, shows the following error:

```
/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2131 [[object Object]]write after end
$onExtensionRuntimeError @ /usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2131
/usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2131 Error [ERR_STREAM_WRITE_AFTER_END]: write after end
	at writeAfterEnd (/usr/share/codium/resources/app/out/vs/code/electron-browser/workbench/_stream_writable.js:266)
	at Socket.Writable.write (/usr/share/codium/resources/app/out/vs/code/electron-browser/workbench/_stream_writable.js:315)
	at /home/eaking/.vscode-oss/extensions/redhat.java-0.79.0/dist/extension.js:2
	at new Promise (<anonymous>)
	at c.write (/home/eaking/.vscode-oss/extensions/redhat.java-0.79.0/dist/extension.js:2)
	at _.doWrite (/home/eaking/.vscode-oss/extensions/redhat.java-0.79.0/dist/extension.js:2)
	at /home/eaking/.vscode-oss/extensions/redhat.java-0.79.0/dist/extension.js:2
$onExtensionRuntimeError @ /usr/share/codium/resources/app/out/vs/workbench/workbench.desktop.main.js:2131
```

**Comment by eakst7** [comment]
@testforstephen

Hi, what additional information would be helpful?  KJNoonan attached the requested logs and I confirmed the same "write after end" error in the DevTools console.

The "Running the contributed command: 'java.execute.workspaceCommand' failed." does not appear in the logs; it is a notification:

![image](https://user-images.githubusercontent.com/16217243/117585314-c4bf5080-b0df-11eb-8a42-079ce97a728d.png)

**Comment by evilguest** [comment]
Having the same problem.
VS Code version 1.60, extension installed last week.
Trying to run debugger yields the following in the Output / Language Support for Java:

```
[Error - 11:31:22 AM] Sep 12, 2021, 11:31:22 AM Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
com/sun/jdi/ClassNotLoadedException
java.lang.NoClassDefFoundError: com/sun/jdi/ClassNotLoadedException
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler$1.acceptSearchMatch(ResolveMainClassHandler.java:103)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.report(MatchLocator.java:2177)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2560)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3290)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2854)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2029)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1345)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1382)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1524)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:250)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:601)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.resolveMainClassCore(ResolveMainClassHandler.java:137)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.computeProposals(ResolveMainClassHandler.java:222)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.validateLaunchConfigCore(ResolveMainClassHandler.java:179)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.validateLaunchConfig(ResolveMainClassHandler.java:70)
	at com.microsoft.java.debug.plugin.internal.JavaDebugDelegateCommandHandler.executeCommand(JavaDebugDelegateCommandHandler.java:74)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:505)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.jdi.ClassNotLoadedException cannot be found by com.microsoft.java.debug.plugin_0.32.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:506)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 30 more

[Error - 11:31:22 AM] Sep 12, 2021, 11:31:22 AM Error in calling delegate command handler
com/sun/jdi/ClassNotLoadedException
java.lang.NoClassDefFoundError: com/sun/jdi/ClassNotLoadedException
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler$1.acceptSearchMatch(ResolveMainClassHandler.java:103)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.report(MatchLocator.java:2177)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2560)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3290)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2854)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2029)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1345)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1382)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1524)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:250)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:601)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.resolveMainClassCore(ResolveMainClassHandler.java:137)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.computeProposals(ResolveMainClassHandler.java:222)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.validateLaunchConfigCore(ResolveMainClassHandler.java:179)
	at com.microsoft.java.debug.plugin.internal.ResolveMainClassHandler.validateLaunchConfig(ResolveMainClassHandler.java:70)
	at com.microsoft.java.debug.plugin.internal.JavaDebugDelegateCommandHandler.executeCommand(JavaDebugDelegateCommandHandler.java:74)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:505)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.jdi.ClassNotLoadedException cannot be found by com.microsoft.java.debug.plugin_0.32.0
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:506)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 30 more
```
