### ISSUE TITLE
command 'vscode.java.startDebugSession' not found

### ISSUE THREAD

**Issue by musiKk** [Microsoft/vscode-java-debug#98]
I just installed the extension via the Java Extensions Pack on an OS X 10.12. On Linux I had good experiences but now I only get the error "command 'vscode.java.startDebugSession' not found" whenever I try to launch an application.

The developer tools spit out the following in the console:

```
messageService.ts:125 command 'vscode.java.startDebugSession' not found: Error: command 'vscode.java.startDebugSession' not found
    at t._tryExecuteCommand (file:///private/var/folders/h_/rzqzz34d2hjdwz1hcdk4kz301b3yzz/T/AppTranslocation/E9ED61E9-D76F-4174-B988-A75B1E3854CF/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:1080410)
    at file:///private/var/folders/h_/rzqzz34d2hjdwz1hcdk4kz301b3yzz/T/AppTranslocation/E9ED61E9-D76F-4174-B988-A75B1E3854CF/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:1080249
    at n.Class.define.cancel.then (file:///private/var/folders/h_/rzqzz34d2hjdwz1hcdk4kz301b3yzz/T/AppTranslocation/E9ED61E9-D76F-4174-B988-A75B1E3854CF/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:60387)
    at t.executeCommand (file:///private/var/folders/h_/rzqzz34d2hjdwz1hcdk4kz301b3yzz/T/AppTranslocation/E9ED61E9-D76F-4174-B988-A75B1E3854CF/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:1080223)
    at file:///private/var/folders/h_/rzqzz34d2hjdwz1hcdk4kz301b3yzz/T/AppTranslocation/E9ED61E9-D76F-4174-B988-A75B1E3854CF/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:383808
    at n.Class.define.cancel.then (file:///private/var/folders/h_/rzqzz34d2hjdwz1hcdk4kz301b3yzz/T/AppTranslocation/E9ED61E9-D76F-4174-B988-A75B1E3854CF/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:60387)
    at file:///private/var/folders/h_/rzqzz34d2hjdwz1hcdk4kz301b3yzz/T/AppTranslocation/E9ED61E9-D76F-4174-B988-A75B1E3854CF/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:383745
    at n.Class.define.cancel.then (file:///private/var/folders/h_/rzqzz34d2hjdwz1hcdk4kz301b3yzz/T/AppTranslocation/E9ED61E9-D76F-4174-B988-A75B1E3854CF/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:60387)
    at file:///private/var/folders/h_/rzqzz34d2hjdwz1hcdk4kz301b3yzz/T/AppTranslocation/E9ED61E9-D76F-4174-B988-A75B1E3854CF/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:383576
    at n.Class.derive._oncancel.then (file:///private/var/folders/h_/rzqzz34d2hjdwz1hcdk4kz301b3yzz/T/AppTranslocation/E9ED61E9-D76F-4174-B988-A75B1E3854CF/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:28:60387)
```

My launch configuration contains nothing special:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "My Application",
            "request": "launch",
            "mainClass": "my.MainClass",
            "args": "",
            "vmArgs": "-Dsome=arg"
        }
    ]
}
```

I don't know what else to provide. Please let me know how I can be of assistance.

**Comment by testforstephen** [comment]
@musiKk Could you share us VSCode version, your debugging project type and the log file? 
You can click `command + shift + P` to pop up a dropdown box, then select `Java: Open Java Language Server log file` to show the log file.

**Comment by musiKk** [comment]
Ok, it turns out, my configuration was wrong. I had some remnants from my previous setup which caused Redhat's Java extension to not work properly. This caused the mentioned behavior. I guess the Java Debugging Extension also failed to load somehow because of that because your proposed command for opening the log also created a similar error than when I tried to launch something.

So I guess I can make it work now. I don't know if you can improve something like showing a better error message. Really appreciate your help. You can close this issue at your discretion. If you still want more info, I'd be happy to assist.

**Comment by testforstephen** [comment]
Good to hear that you fix it by yourself. The java debugger extension works as a plugin of Redhat's Java extension. So if that extension failed to activate, the debugger would not work either.

This is an activation issue, and the error message is from VSCode code. No way to change it on debugger. Besides, any code on debugger extension would not be executed if the depended extensions cannot be activated.
